steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/shoplc-amazon-reviews/shoplc-amazon-reviews/shoplc-amazon-reviews:latest'
      - '.'
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/shoplc-amazon-reviews/shoplc-amazon-reviews/shoplc-amazon-reviews:latest'
  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'shoplc-amazon-reviews'
      - '--image=us-central1-docker.pkg.dev/shoplc-amazon-reviews/shoplc-amazon-reviews/shoplc-amazon-reviews:latest'
      - '--platform=managed'
      - '--region=us-central1'
